/*
PROBLEM DESCRIPTION:

"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."

 */

class Euler2 {
	
	public static int evenFibs( ) {

		boolean flip = true;
		int first = 1;
		int second = 0;
		int fib = 0;
		int acc = 0;

		while( fib < 4000000 ) {
			fib = first + second;

			if ( ( fib % 2 ) == 0 )
				acc = acc + fib;

			if( flip ) {
				first = fib;
				flip = false;
			} else {
				second = fib;
				flip = true;
			}
		}

		return acc;

	}


	public static void main( String[] args ) {

		System.out.println("The sum of all the even Fibs less than 4 million is " + evenFibs( ) );

	}

}